### ISSUE TITLE
For Mon Feb. 27

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#53]
# Monday Commitments
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face:  | PCA vs. RPCA on entire data set, with all metrics reported. Affirmative determination of which we should use. | @rmarren1 [ipybn](https://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/RPCA_vs._PCA_Final.ipynb) [old ipynb for comparison](https://github.com/NeuroDataDesign/orange-panda/blob/81a8fc1228e508ed0f5e55f532399b29383e3a3e/notes/noise_reduction/Noise%20Reduction%20Benchmarking.ipynb) |
| :hourglass: | Measure discriminibility of the interpolations done by Nicolas, determine whether it helped. If so, attempt to re-create results with our data and interpolation method. | @rmarren1 [ipybn](https://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/interpolation/Int_2.ipynb)  |
| 🐼  | Test alignment code for EEG data on all trials of one subject and a few other subjects. If it doesn't work uniformly, fix it such that Nicholas' data can all be automatically aligned into trials. | [.ipynb](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/o4ko14wlsa944yl/EEGTrialAlignment%20%284%29.ipynb) @tsunwong123 |
| :x: | (Reach Goal) Align eye-tracking data (i.e. saccades, blinks, vs fixations) to the EEG data using time stamps. |@tsunwong123 |
| :hourglass: | Identify different metrics that may identify bad electrodes and use them together to identify electrodes | [.ipynb](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/ExploratoryNicolasFormat-Copy1.ipynb) @nkumarcc |

# Thursday Checkpoint
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face: | Set up the Auto-Bench tool in Cortex (rather than UGRAD) and refactor with new ideas developed while using it. Create a generator which pulls data directly from AWS if it is not ok to download the entire data set on Cortex (50+ Gigs).| @rmarren1|
| ⏳   | Make it clear that alignment on EEG data works. Find some way to show that | [.ipynb](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/analysis/LabelingEEGData%20%281%29.ipynb) @tsunwong123 |
| ⌛️ | Plot several bad electrodes for Nicolas and Kara, identify some consistent properties | [.ipynb](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/ExploratoryNicolasFormat.ipynb) @nkumarcc |

**Comment by rmarren1** [comment]
@gkiar @nkumarcc @tsunwong123

**Comment by gkiar** [comment]
- @rmarren1:
  - I suggest benchmarking on a subset of data rather than the full dataset, so you probably don't need 50 GB of data for that, no?
- @tsunwong123:
  - "Test multiple subjects on the code for aligning the trials." what does this mean? Is this code written already? If so, then wasn't it tested then? If not, then isn't the task "writing" not "testing"? I'm unclear on what you're going to do.
  - "Try" is too weak for a commitment. What are you going to show?
- @nkumarcc:
  - cool, how are you going to split up the statistics? For instance, using multiple features may be useful, and some may be more like those "manually" detected, and others more like those "automatically" detected with current methods. How will you decide which statistics, how many, threshold levels, etc.? Is it more important to not miss a bad electrode or to exclude a good electrode? (I suggest using precision-recall, and picking an operating point that puts you a place on the F1 curve that you can justify)

**Comment by tsunwong123** [comment]
@gkiar Yeah sorry that it was worded ambiguously. The code was the alignment task last week. It was tested on one subject and only the visual and resting paradigms (Nicholas's old data) but I need to download more subjects to check if it works using the public S3 key they have now (checking on other subjects and also other trials beside resting ones).  If not, then I will have to change it to make sure it works on all trials and subjects

**Comment by gkiar** [comment]
@nkumarcc:
We have decided for you to curate the following with a plot for all of the below with both time series and power spectrum:

| Number of electrodes | Processed as | We believe |
|-------------------------|-----------------|----------------|
| 5 | good (by both us and nicolas) | good |
| 5 | good (by both us and nicolas) | bad |
| 5 | bad (by nicolas automatic) | bad |
| 5 | bad (by nicolas automatic) | good |
| 5 | bad (by nicolas manual) | bad |
| 5 | bad (by nicolas manual) | good |
| 5 | bad (by us) | bad |
| 5 | bad (by us) | good |

This will be then brought to nicolas and discussed, and become the authority on bad electrode detection.
